### ISSUE TITLE
但是水平有限，能请教一下么，非常感谢

### ISSUE THREAD

**Issue by guxianxiong** [prinsun/MKXEventBus#1]
看了你的《ObjC 基于上下文的设计》，受益匪浅。
1. iOS上下文在开发中更多被运用到的列子么？
2. MKXEventBus是被用来替代Notification的，你文中指的“Notification 太弱，类型太弱，需要太多的约定”是什么意思？能具体描述下么
3. MKXEventBus中的上下文具体应用是哪块？是指在subscribe方法的block中，将event返回出去么？

**Comment by prinsun** [comment]
谢谢关注。
1. 首先一个概念我并不希望被强制的使用到某个地方，应该是觉得合适的时候，自然的去使用。上下文用于**隔离存储**，所以可以用在：**一系列通用的方法封装，方法的行为依赖一些全局的状态，这些全局状态便可以存在上下文中**，理解**隔离**，最好的例子就是事务。
2. 我所指的是 Notification 所携带的数据是非强类型（id、dictionary），如果缺乏双方的约定，很难知道它具体代表的意思。
3. 在`MKXEventBus`中，上下文用于存储订阅者执行`block`的`dispatch_queue`，也就是事件发布后，订阅者的`block`会在指定的队列得到执行，默认是主队列。

比如：

``` objc
[MKXEventBus beginSubscribe:dispatch_get_main_queue()]; // block1 和 block2 都在主队列执行
[[MKXEventBus sharedBus] subscribe:MKXLoginSuccessEvent.class for:self with:block1];
[[MKXEventBus sharedBus] subscribe:MKXLogoutSuccessEvent.class for:self with:block2];
[MKXEventBus endSubscribe];

[MKXEventBus beginSubscribe:dispatch_get_global_queue(0, 0)]; // block3 和 block4 都在全局队列执行
[[MKXEventBus sharedBus] subscribe:MKXLoginSuccessEvent.class for:self with:block3];
[[MKXEventBus sharedBus] subscribe:MKXLogoutSuccessEvent.class for:self with:block4];
[MKXEventBus endSubscribe];
```

**Comment by guxianxiong** [comment]
没想到反馈的这么快，非常感谢
你的解释对我更好的理解帮助非常大，再次感谢
